# Default values for myapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: IMAGE_NAME
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: IMAGE_TAG

service:
  type: NodePort
  port: 8080

# Add resource limits and requests for CPU and Memory
resources:
  limits:
    cpu: "0.5"
    memory: "256Mi"
  requests:
    cpu: "0.1"
    memory: "128Mi"

# Add securityContext for the containers
securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
